### ISSUE TITLE
Lag issue when loading from FirstViewController

### ISSUE THREAD

**Issue by icecodetim** [BTLibrary/BTGlassScrollView#1]
Thanks so much for sharing this. It's fantastic.

There is a significant lag when I hit "GO TO THE MAIN APP" in FirstViewController. It loads the views but if you go back and press it again there's another lag to load them.

Any suggestions on how to remove the lag?

Cheers
Tim

**Comment by BTLibrary** [comment]
Hi Tim,

Thanks for testing it out. The example provided is in no way optimized. It is very simple and a straight forward way to use BTGlassScrollView class. There are numerous ways you can optimize this approach. To name a few: 

(1) instead of creating new ViewController every time, just reuse the same one, 
(2) use horizontal table view with JIT optimization instead of UIScrollView to compose multiple BTGlassScrollView, 
(3) create foregroundView asynchronously, 
(4) change the blurring code into background thread. 

I did not do any of that to keep the implementation as simple as possible, so people can easily grasp the basics of each components. 

Of course, you would need to do the optimizations before you release it into the wild. If you need help with anything specific, or have any improvement you have in mind, let me know. I am always open and happy to help. 

Cheers!
Byte

**Comment by icecodetim** [comment]
Great, thanks Byte. I've gone with option 1 and it's working like a dream. Keep up the great work!

PS Any ideas on how one might add a parallax effect where the background picture moves slightly in response to device rotation?

**Comment by BTLibrary** [comment]
Unfortunately, it is a design decision that BTGlassScrollView is created to not have parallax effect. This is because I do not see any value to the parallax effect (I have "Reduced Motion" on). So, there is no one liner to create the effect. 

However, there is nothing to stop you from implementing it. You need to do 2 things to create the effect. 
(1) change the size of the backgroundView/foregroundView to accommodate the movement effect
(2) add motion effect onto the backgroundView/foreground. Either use the UIMotionEffect or this gent's repo (https://github.com/michaeljbishop/NGAParallaxMotion). He has created a neat one liner to add the effect onto any view. 

Personally though, I think the effect feels sluggish and gimmicky. I would not add it on unless there is a really good reason to. 

Good luck,
Byte

**Comment by felipecastro** [comment]
Hi, I really enjoyed this control and I intend to use it in my project, how do you think is the best way to implement asynchronous loading image for backgroundView?

thanks!

**Comment by BTLibrary** [comment]
Hi there Felipecastro, 

Thanks for using it. Sorry for the late reply. You can overwrite setter for backgroundImage to update the view. Animation or otherwise can be executed there. Once you do have the method in place, you can just set it when the asynchronous image is loaded. Please open a new question if you have question (I prefer you don't hijack Tim's thread ;) ). 

Byte
